### ISSUE TITLE
Wrong spaces

### ISSUE THREAD

**Issue by computan** [computan/adiantmarketing-JP-Griffin-Email-Template#3]
wrong space
http://prntscr.com/m7yxep + http://prntscr.com/m7z64d + http://prntscr.com/m8057j + http://prntscr.com/m808bg + http://prntscr.com/m809j1 +http://prntscr.com/m7yu4y

**Comment by computan** [comment]
Done

**Comment by asif-mahmood-com** [comment]
Done
